services:
  playwright:
    image: mcr.microsoft.com/playwright:v1.54.0-noble
    working_dir: /app
    volumes:
      - ./:/app
    command: npx playwright test
    environment:
      - HOME=/root
    tty: true
    # Uncomment the following lines if you want to run headed (with GUI) tests
    # environment:
    #   - DISPLAY
    #   - PWDEBUG=1
    # devices:
    #   - "/dev/dri:/dev/dri"
    # ports:
    #   - "9222:9222"
