services:
  playwright:
    image: mcr.microsoft.com/playwright:v1.54.0-noble
    working_dir: /app
    volumes:
      - ./:/app
    command: npx playwright test
    environment:
      - HOME=/root
      - CI=true
    tty: true
    ports:
      - '9323:9323'
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /srv/app
    volumes:
      - ./:/srv/app
    ports:
      - '3000:3000'
    environment:
      - APP_ENV=test
    command: npm start
