import type { Metadata } from 'next'
import './globals.css'
import { Header } from '@/src/components/Header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <Header>
          <h1>User Directory</h1>
        </Header>
        <main>{children}</main>
      </body>
    </html>
  )
}
