import { UserData } from '.'

export const stub: UserData[] = [
  {
    id: '980b82bf-d1af-4e66-ab93-004da059b275',
    username: 'nberwick0',
    firstname: 'Norton',
    lastname: 'Berwick',
    email: 'nberwick0@liveinternet.ru',
    avatar: 'https://robohash.org/illumvitaeea.png?size=50x50&set=set1',
    role: 'Subcontractor',
    join_date: '5/4/2023',
    description:
      'Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.',
  },
  {
    id: '4348814a-4ab9-4302-b1a0-93b6910080e0',
    username: 'rgatfield1',
    firstname: 'Rouvin',
    lastname: 'Gatfield',
    email: 'rgatfield1@state.gov',
    avatar: 'https://robohash.org/utcorruptiducimus.png?size=50x50&set=set1',
    role: 'Engineer',
    join_date: '2/28/2024',
    description:
      'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.',
  },
  {
    id: 'b79011a4-3bd9-4a48-bdea-8b2ee14ce7dd',
    username: 'bhancke2',
    firstname: 'Bari',
    lastname: 'Hancke',
    email: 'bhancke2@bloglovin.com',
    avatar: 'https://robohash.org/nesciuntquaetotam.png?size=50x50&set=set1',
    role: 'Engineer',
    join_date: '4/16/2024',
    description:
      'Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.',
  },
  {
    id: '215ea5fc-3acf-47f0-802c-39fd72b0aa15',
    username: 'sgolagley3',
    firstname: 'Sergeant',
    lastname: 'Golagley',
    email: 'sgolagley3@multiply.com',
    avatar: 'https://robohash.org/repellatsuntnesciunt.png?size=50x50&set=set1',
    role: 'Electrician',
    join_date: '4/1/2024',
    description:
      'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.',
  },
  {
    id: '8de05533-6cd3-42fb-a4bc-e8817400bd09',
    username: 'cdakers4',
    firstname: 'Cherish',
    lastname: 'Dakers',
    email: 'cdakers4@joomla.org',
    avatar:
      'https://robohash.org/repellatconsequunturea.png?size=50x50&set=set1',
    role: 'Surveyor',
    join_date: '8/13/2023',
    description:
      'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.',
  },
  {
    id: 'ae3db8b5-cff4-468a-b98e-ba0440c00ca0',
    username: 'awestwater5',
    firstname: 'Alyda',
    lastname: 'Westwater',
    email: 'awestwater5@cdc.gov',
    avatar: 'https://robohash.org/nequealiquamnon.png?size=50x50&set=set1',
    role: 'Surveyor',
    join_date: '5/21/2023',
    description:
      'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.',
  },
  {
    id: '3f3dc783-70db-44ed-8e26-8512fe8f94e9',
    username: 'dwaghorne6',
    firstname: 'Diarmid',
    lastname: 'Waghorne',
    email: 'dwaghorne6@dyndns.org',
    avatar: 'https://robohash.org/etconsequuntursed.png?size=50x50&set=set1',
    role: 'Architect',
    join_date: '8/21/2023',
    description:
      'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.',
  },
  {
    id: 'dc459fa2-90d8-4ee4-86d9-4914f4f2c7ca',
    username: 'hplenderleith7',
    firstname: 'Honoria',
    lastname: 'Plenderleith',
    email: 'hplenderleith7@uiuc.edu',
    avatar:
      'https://robohash.org/beataerecusandaeomnis.png?size=50x50&set=set1',
    role: 'Engineer',
    join_date: '8/12/2023',
    description:
      'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.',
  },
  {
    id: '35156833-c179-4dc7-81e3-0091b5e184c9',
    username: 'iomara8',
    firstname: 'Ivett',
    lastname: "O'Mara",
    email: 'iomara8@technorati.com',
    avatar: 'https://robohash.org/earumenimquam.png?size=50x50&set=set1',
    role: 'Engineer',
    join_date: '10/8/2023',
    description:
      'Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.',
  },
  {
    id: '1cbdd548-6299-45ec-bb23-eacc8dc9a5c5',
    username: 'fgrist9',
    firstname: 'Faye',
    lastname: 'Grist',
    email: 'fgrist9@edublogs.org',
    avatar:
      'https://robohash.org/estdoloribusconsequatur.png?size=50x50&set=set1',
    role: 'Surveyor',
    join_date: '7/22/2023',
    description:
      'Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.',
  },
  {
    id: '91c75922-9e47-4bb4-85cd-0aea7f6c1884',
    username: 'vmcrobertsa',
    firstname: 'Valeria',
    lastname: 'McRoberts',
    email: 'vmcrobertsa@indiatimes.com',
    avatar: 'https://robohash.org/assumendaquosqui.png?size=50x50&set=set1',
    role: 'Engineer',
    join_date: '5/8/2023',
    description:
      'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.',
  },
  {
    id: 'cdd32140-ff37-45e3-870d-9193601a469b',
    username: 'mpaffordb',
    firstname: 'Misha',
    lastname: 'Pafford',
    email: 'mpaffordb@princeton.edu',
    avatar: 'https://robohash.org/etconsequaturut.png?size=50x50&set=set1',
    role: 'Estimator',
    join_date: '3/20/2024',
    description:
      'Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.',
  },
  {
    id: 'a08cf201-e43f-477d-bc8d-7dd16c1985d0',
    username: 'sallanc',
    firstname: 'Sly',
    lastname: 'Allan',
    email: 'sallanc@fastcompany.com',
    avatar:
      'https://robohash.org/consequaturducimusoptio.png?size=50x50&set=set1',
    role: 'Subcontractor',
    join_date: '7/23/2023',
    description:
      'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.',
  },
  {
    id: '48fdb8fd-af8d-4c70-a22e-d1026d0fdecd',
    username: 'kdosdilld',
    firstname: 'Kalina',
    lastname: 'Dosdill',
    email: 'kdosdilld@mapy.cz',
    avatar: 'https://robohash.org/abprovidentratione.png?size=50x50&set=set1',
    role: 'Estimator',
    join_date: '12/9/2023',
    description: 'In eleifend quam a odio.',
  },
  {
    id: 'da8b42a4-66b9-4beb-b3a1-140ae2bea44d',
    username: 'pormistonee',
    firstname: 'Phaidra',
    lastname: 'Ormistone',
    email: 'pormistonee@drupal.org',
    avatar: 'https://robohash.org/etminussimilique.png?size=50x50&set=set1',
    role: 'Engineer',
    join_date: '2/24/2024',
    description:
      'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.',
  },
  {
    id: 'a35e7364-5247-4f69-b50b-8a6ee6fa0c26',
    username: 'dcardof',
    firstname: 'Derry',
    lastname: 'Cardo',
    email: 'dcardof@boston.com',
    avatar: 'https://robohash.org/eosdoloremquequos.png?size=50x50&set=set1',
    role: 'Surveyor',
    join_date: '8/4/2023',
    description:
      'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.',
  },
  {
    id: '48b4c846-3feb-461b-a896-fdafbe190bf0',
    username: 'talsobrookg',
    firstname: 'Thom',
    lastname: 'Alsobrook',
    email: 'talsobrookg@prweb.com',
    avatar: 'https://robohash.org/veroiustoquia.png?size=50x50&set=set1',
    role: 'Engineer',
    join_date: '2/17/2024',
    description:
      'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.',
  },
  {
    id: '821aa46e-5df4-40ab-98d8-3063f5c1b512',
    username: 'akarysh',
    firstname: 'Arthur',
    lastname: 'Karys',
    email: 'akarysh@npr.org',
    avatar:
      'https://robohash.org/veniamsimiliquecupiditate.png?size=50x50&set=set1',
    role: 'Project Manager',
    join_date: '11/18/2023',
    description:
      'Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.',
  },
  {
    id: '2b91b764-6998-4ba2-90d9-71d8eb3a7344',
    username: 'zlancasteri',
    firstname: 'Zebedee',
    lastname: 'Lancaster',
    email: 'zlancasteri@gmpg.org',
    avatar:
      'https://robohash.org/iuredoloribuspariatur.png?size=50x50&set=set1',
    role: 'Subcontractor',
    join_date: '11/21/2023',
    description:
      'Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.',
  },
  {
    id: 'a38acd59-351a-4b5f-8a5d-67c6ebae4da2',
    username: 'hbatchelorj',
    firstname: 'Herb',
    lastname: 'Batchelor',
    email: 'hbatchelorj@go.com',
    avatar: 'https://robohash.org/autemtotamet.png?size=50x50&set=set1',
    role: 'Electrician',
    join_date: '1/14/2024',
    description:
      'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.',
  },
  {
    id: '4425c4ab-2533-4b7e-ab51-dd3cbf220f8a',
    username: 'lhazlewoodk',
    firstname: 'Lennard',
    lastname: 'Hazlewood',
    email: 'lhazlewoodk@jiathis.com',
    avatar:
      'https://robohash.org/pariaturatqueinventore.png?size=50x50&set=set1',
    role: 'Construction Manager',
    join_date: '4/18/2024',
    description:
      'Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
  },
  {
    id: '2e45209c-7915-4a38-9d2d-a73770245fc0',
    username: 'tmalserl',
    firstname: 'Therine',
    lastname: 'Malser',
    email: 'tmalserl@myspace.com',
    avatar: 'https://robohash.org/sedipsanon.png?size=50x50&set=set1',
    role: 'Construction Expeditor',
    join_date: '11/28/2023',
    description: 'Curabitur in libero ut massa volutpat convallis.',
  },
  {
    id: 'a15a7ce3-7863-4ba5-ba9a-77810f96db30',
    username: 'jlantaffm',
    firstname: 'Jewel',
    lastname: 'Lantaff',
    email: 'jlantaffm@skype.com',
    avatar: 'https://robohash.org/nonillumnisi.png?size=50x50&set=set1',
    role: 'Supervisor',
    join_date: '6/9/2023',
    description:
      'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.',
  },
  {
    id: 'd53063bf-90fc-4aa4-8ea0-b2c3c1866a29',
    username: 'kpoundsfordn',
    firstname: 'Karrah',
    lastname: 'Poundsford',
    email: 'kpoundsfordn@cpanel.net',
    avatar: 'https://robohash.org/noninofficia.png?size=50x50&set=set1',
    role: 'Project Manager',
    join_date: '9/29/2023',
    description:
      'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.',
  },
  {
    id: '1413f2f7-a8c7-4777-8764-f9f331d348e7',
    username: 'inibleyo',
    firstname: 'Iago',
    lastname: 'Nibley',
    email: 'inibleyo@ibm.com',
    avatar: 'https://robohash.org/eosmagniratione.png?size=50x50&set=set1',
    role: 'Engineer',
    join_date: '4/10/2024',
    description:
      'Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.',
  },
  {
    id: '207e6305-e37b-4596-82d6-e52b0de3c1b3',
    username: 'tduffittp',
    firstname: 'Theadora',
    lastname: 'Duffitt',
    email: 'tduffittp@gmpg.org',
    avatar: 'https://robohash.org/delenitiestdelectus.png?size=50x50&set=set1',
    role: 'Electrician',
    join_date: '10/13/2023',
    description:
      'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.',
  },
  {
    id: '620ec8de-1d5a-44b6-ad5a-49b72c087bd8',
    username: 'dschulerq',
    firstname: 'Delmar',
    lastname: 'Schuler',
    email: 'dschulerq@symantec.com',
    avatar: 'https://robohash.org/odioautemrepudiandae.png?size=50x50&set=set1',
    role: 'Construction Manager',
    join_date: '7/18/2023',
    description:
      'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.',
  },
  {
    id: '7f619cdd-3856-464a-b73e-87f40f50a7a6',
    username: 'jmoraleer',
    firstname: 'Jillayne',
    lastname: 'Moralee',
    email: 'jmoraleer@cloudflare.com',
    avatar: 'https://robohash.org/quiplaceatquis.png?size=50x50&set=set1',
    role: 'Engineer',
    join_date: '10/29/2023',
    description:
      'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.',
  },
  {
    id: '30e8c6f9-ad71-409d-a1fe-31b9cf8930f0',
    username: 'mlocheads',
    firstname: 'Marylee',
    lastname: 'Lochead',
    email: 'mlocheads@smh.com.au',
    avatar: 'https://robohash.org/voluptassedmolestiae.png?size=50x50&set=set1',
    role: 'Construction Expeditor',
    join_date: '11/27/2023',
    description:
      'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.',
  },
  {
    id: 'fa7e53b7-1933-4438-bcd3-6d154f5d0e66',
    username: 'hfearnallt',
    firstname: 'Harv',
    lastname: 'Fearnall',
    email: 'hfearnallt@uol.com.br',
    avatar: 'https://robohash.org/nonharumnatus.png?size=50x50&set=set1',
    role: 'Estimator',
    join_date: '9/2/2023',
    description:
      'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.',
  },
  {
    id: 'c6ef52b6-2875-413b-a88c-af678b8422d9',
    username: 'etetheru',
    firstname: 'Elijah',
    lastname: 'Tether',
    email: 'etetheru@independent.co.uk',
    avatar: 'https://robohash.org/reiciendisomnisatque.png?size=50x50&set=set1',
    role: 'Construction Foreman',
    join_date: '10/25/2023',
    description:
      'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.',
  },
  {
    id: '3a5cb182-0807-4c94-b916-6a0a706080b7',
    username: 'tjeffordv',
    firstname: 'Travis',
    lastname: 'Jefford',
    email: 'tjeffordv@jimdo.com',
    avatar: 'https://robohash.org/autlaboreitaque.png?size=50x50&set=set1',
    role: 'Project Manager',
    join_date: '3/4/2024',
    description:
      'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.',
  },
  {
    id: 'c63e650f-0fc2-4e1c-b9f9-6e9e28d35104',
    username: 'rsibsonw',
    firstname: 'Roderigo',
    lastname: 'Sibson',
    email: 'rsibsonw@t.co',
    avatar: 'https://robohash.org/etvitaeearum.png?size=50x50&set=set1',
    role: 'Project Manager',
    join_date: '3/20/2024',
    description:
      'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.',
  },
  {
    id: '0809d4aa-472d-452b-ac3f-3f42fc44320b',
    username: 'gkennetx',
    firstname: 'Gerhardt',
    lastname: 'Kennet',
    email: 'gkennetx@prnewswire.com',
    avatar: 'https://robohash.org/abexplicaboet.png?size=50x50&set=set1',
    role: 'Project Manager',
    join_date: '9/3/2023',
    description:
      'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.',
  },
  {
    id: '0b9148e8-6ad8-4758-b7ad-6c164834484f',
    username: 'pstodharty',
    firstname: 'Putnam',
    lastname: 'Stodhart',
    email: 'pstodharty@google.pl',
    avatar: 'https://robohash.org/animiautqui.png?size=50x50&set=set1',
    role: 'Construction Expeditor',
    join_date: '9/27/2023',
    description:
      'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.',
  },
  {
    id: 'af3f021e-9037-43c4-b626-33ce70e912dd',
    username: 'rambresinz',
    firstname: 'Ronnie',
    lastname: 'Ambresin',
    email: 'rambresinz@arizona.edu',
    avatar: 'https://robohash.org/utconsequaturquos.png?size=50x50&set=set1',
    role: 'Subcontractor',
    join_date: '12/16/2023',
    description:
      'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.',
  },
]
